import type { Metadata, Viewport } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  adjustFontFallback: true,
  fallback: ["sans-serif"],
});
export const metadata: Metadata = {
  title: "TesseractApps",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased max-w-[1920px] m-auto`}>
        <Navbar />
        <div className="min-h-[780px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
